# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  apilogin:
    image: apilogin
    build:
      context: .
      dockerfile: APILogin/Dockerfile
    ports:
      - 5135:5135
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
