version: "3.7"

volumes:
  kong_data: {}
  users_data: {}

networks: #Red interna para comunicar los servicios (“Services on the same network can communicate with each other using their name”)
  kong-net:

services:
  front:
    image: my-angular-app
    build:
      context: ./RestClientPractica
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - "4200:80"
    networks:
      - kong-net

  Login-API:
    image: login-api-image
    build:
      context: ./APILogin
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - "5121:80"
    networks:
      - kong-net
    depends_on:
      - Users-API

  Users-API:
    image: users-api-image
    build:
      context: ./APIPractica
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - kong-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://Usuarios-database:3306/Usuarios?createDatabaseIfNotExist=true
    depends_on:
      - Usuarios-database

  Usuarios-database:
    image: mysql
    hostname: Usuarios-database
    cap_add:
      - SYS_NICE
    restart: unless-stopped
    ports:
      - "3307:3306"
    networks:
      - kong-net
    volumes:
      - users_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: Usuarios
      MYSQL_ROOT_HOST: "%"
